// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqyibbrwoarctsdszmkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxeWliYnJ3b2FyY3RzZHN6bWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Njc0NDYsImV4cCI6MjA3MjE0MzQ0Nn0.VJLG_Jf2G64TvHUadSmLDH58kWZofNlnxcGeT4qths8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});